// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  docSidebar: [
    {
      type: "doc",
      id: "overview",
      label: "Overview",
    },
    {
      type: "category",
      label: "How To",
      link: {
        type: "generated-index",
        slug: "HowTo",
      },
      items: [
        {
          type: "autogenerated",
          dirName: "HowTo",
        },
      ],
    },
    {
      type: "category",
      label: "Concepts",
      link: {
        type: "generated-index",
        slug: "Concepts",
      },
      items: [
        {
          type: "autogenerated",
          dirName: "Concepts",
        },
      ],
    },
    {
      type: "category",
      label: "Tutorials",
      link: {
        type: "generated-index",
        slug: "Tutorials",
      },
      items: [
        {
          type: "autogenerated",
          dirName: "Tutorials",
        },
      ],
    },
    {
      type: "category",
      label: "Reference",
      link: {
        type: "generated-index",
        slug: "Reference",
      },
      items: [
        {
          type: "autogenerated",
          dirName: "Reference",
        },
      ],
    },
  ],
};

module.exports = sidebars;
