---
name: Publish PR preview

on: [ pull_request ]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: preview
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: checkout code from repos
        uses: actions/checkout@v3
        with:
          persist-credentials: false
          ref: refs/pull/${{ github.event.number }}/merge # required to pull the PR code instead of the main one
          fetch-depth: 0 # Required for mkdocs to be able to display pages last update info

      - name: Build and publish PR preview
        uses: ConsenSys/doctools.action-builder/actions/pr-preview-publish@main
        with:
          BRANCH: 'pr-preview'
